const $ = id => document.getElementById(id);
const status = text => { $('status').textContent = text; };
const sleep = ms => new Promise(r => setTimeout(r, ms));
async function run(tabId, func, args = []) { const result = await chrome.scripting.executeScript({target:{tabId},func,args}); return result?.[0]?.result; }
async function waitForOPM(tabId, test, timeout=30000) { const started=Date.now(); while(Date.now()-started<timeout){ try{if(await run(tabId,test))return true;}catch(_){} await sleep(400);} throw new Error('OPM page did not become ready after postback.'); }
const setDate = date => { const el=document.querySelector('#txtTaskDate'); if(!(el instanceof HTMLInputElement))throw new Error('OPM date field not found.'); el.value=date; el.dispatchEvent(new Event('change',{bubbles:true})); return true; };
// Trigger the real select's onchange. OPM's inline onchange calls __doPostBack in page context;
// calling __doPostBack directly from an extension isolated world is unreliable.
const changeSelect = (selector,value,label) => { const el=document.querySelector(selector); if(!(el instanceof HTMLSelectElement))throw new Error(`${label} field not found.`); const opt=[...el.options].find(o=>o.value===String(value)); if(!opt)throw new Error(`${label} option not found: ${value}`); el.value=opt.value; el.dispatchEvent(new Event('change',{bubbles:true})); return opt.textContent.trim(); };
const projectReady = () => { const p=document.querySelector('#ddlProj'); return p instanceof HTMLSelectElement && p.value==='417' && !!document.querySelector('#ddlTaskType'); };
const typeReady = () => { const t=document.querySelector('#ddlTaskType'); return t instanceof HTMLSelectElement && t.value==='M' && !!document.querySelector('#ddlTaskCat'); };
const fillCategoryAndHours = hours => { const cat=document.querySelector('#ddlTaskCat'); if(!(cat instanceof HTMLSelectElement))throw new Error('Task Category field not found.'); if(![...cat.options].some(o=>o.value==='22'))throw new Error('Test Case Execution category not found.'); cat.value='22'; cat.dispatchEvent(new Event('change',{bubbles:true})); const input=document.querySelector('#txtHrs'); if(!(input instanceof HTMLInputElement))throw new Error('Hours field not found.'); input.value=String(hours); input.dispatchEvent(new Event('input',{bubbles:true})); input.dispatchEvent(new Event('change',{bubbles:true})); input.dispatchEvent(new Event('blur',{bubbles:true})); return true; };
const openTaskSearch = ticketId => { const select=document.querySelector('#ddlTask'); if(select instanceof HTMLSelectElement){ const opt=[...select.options].find(o=>o.value===ticketId||o.textContent.trim()===ticketId||o.textContent.includes(ticketId)); if(!opt)throw new Error(`Task not found: ${ticketId}`); select.value=opt.value; select.dispatchEvent(new Event('change',{bubbles:true})); return 'native'; } const box=document.querySelector('#select2-ddlTask-container'); const trigger=box?.closest('.select2-selection'); if(!(trigger instanceof HTMLElement))throw new Error('OPM Task Select2 control not found.'); trigger.click(); return 'select2'; };
const searchTask = ticketId => { const search=document.querySelector('.select2-container--open .select2-search__field'); if(!(search instanceof HTMLInputElement))throw new Error('OPM Task search field not found.'); search.value=ticketId; search.dispatchEvent(new Event('input',{bubbles:true})); search.dispatchEvent(new KeyboardEvent('keyup',{bubbles:true,key:'a',code:'KeyA'})); return true; };
const selectTaskAndSave = async ticketId => { const native=document.querySelector('#ddlTask'); if(native instanceof HTMLSelectElement){ const selected=native.selectedOptions?.[0]; if(!selected||!selected.textContent.includes(ticketId))throw new Error(`Task selection failed: ${ticketId}`); } else { const started=Date.now(); let match=null; while(Date.now()-started<15000){ const open=document.querySelector('.select2-container--open'); const opts=open?[...open.querySelectorAll('.select2-results__option')]:[]; match=opts.find(o=>o.textContent.trim()===ticketId||o.textContent.includes(ticketId)); if(match)break; await sleep(300); } if(!match)throw new Error(`Task result not found: ${ticketId}`); match.click(); const rendered=document.querySelector('#select2-ddlTask-container'); if(!(rendered instanceof HTMLElement)||!rendered.textContent.includes(ticketId))throw new Error(`Task was not selected: ${ticketId}`); } const save=document.querySelector('#LnkSave'); if(!(save instanceof HTMLElement))throw new Error('OPM Save button not found.'); save.click(); return true; };
const saveCompleted = () => { const modal=document.querySelector('#myNewModal'); const save=document.querySelector('#LnkSave'); return !modal || !(save instanceof HTMLElement) || getComputedStyle(modal).display==='none'; };
chrome.tabs.query({active:true,currentWindow:true},([tab])=>{ const d=new Date(); d.setMinutes(d.getMinutes()-d.getTimezoneOffset()); $('date').value=d.toISOString().slice(0,10); $('start').addEventListener('click',async()=>{ if(!tab?.id)return status('OPM tab not found.'); const date=$('date').value; const rows=$('tickets').value.split(/\r?\n/).map(x=>x.trim()).filter(Boolean).map(line=>{const [id,hours]=line.split('|').map(v=>v.trim());return{id,hours};}); if(!date)return status('Select OPM date.'); if(!rows.length||rows.some(r=>!r.id||!r.hours))return status('Use: TICKET | HOURS'); try{ for(let i=0;i<rows.length;i++){const t=rows[i]; status(`Ticket ${i+1}/${rows.length}: ${t.id}\nSetting date...`); await run(tab.id,setDate,[date]); status(`Ticket ${i+1}/${rows.length}: ${t.id}\nSelecting Raj ERP 4.0...`); await run(tab.id,changeSelect,['#ddlProj','417','Project']); await waitForOPM(tab.id,projectReady); status(`Ticket ${i+1}/${rows.length}: ${t.id}\nSelecting SES...`); await run(tab.id,changeSelect,['#ddlTaskType','M','Task Type']); await waitForOPM(tab.id,typeReady); status(`Ticket ${i+1}/${rows.length}: ${t.id}\nFilling category and hours...`); await run(tab.id,fillCategoryAndHours,[t.hours]); status(`Ticket ${i+1}/${rows.length}: ${t.id}\nOpening task search...`); const mode=await run(tab.id,openTaskSearch,[t.id]); if(mode==='select2')await run(tab.id,searchTask,[t.id]); status(`Ticket ${i+1}/${rows.length}: ${t.id}\nSelecting task and saving...`); await run(tab.id,selectTaskAndSave,[t.id]); status(`Ticket ${i+1}/${rows.length}: ${t.id}\nWaiting for Save confirmation...`); await waitForOPM(tab.id,saveCompleted,20000); } status(`Done: ${rows.length} ticket(s) saved.`); }catch(e){status(`Stopped: ${e instanceof Error?e.message:String(e)}`);} }); });
