const $=id=>document.getElementById(id);const status=t=>{$('status').textContent=t};const sleep=ms=>new Promise(r=>setTimeout(r,ms));async function run(tabId,func,args=[]){const r=await chrome.scripting.executeScript({target:{tabId},func,args});return r?.[0]?.result}
const setDate=date=>{const e=document.querySelector('#txtTaskDate');if(!(e instanceof HTMLInputElement))throw Error('OPM date field not found.');e.value=date;e.dispatchEvent(new Event('change',{bubbles:true}));return true};
const changeSelect=(sel,val,setter)=>{const e=document.querySelector(sel);if(!(e instanceof HTMLSelectElement))throw Error(`Field not found: ${sel}`);e.value=String(val);if(typeof window[setter]==='function')window[setter]();e.dispatchEvent(new Event('change',{bubbles:true}));return true};
const projectState=()=>{const e=document.querySelector('#ddlProj');return e instanceof HTMLSelectElement?e.value:null};const typeState=()=>{const e=document.querySelector('#ddlTaskType');return e instanceof HTMLSelectElement?e.value:null};
const categoryHours=hours=>{const c=document.querySelector('#ddlTaskCat');if(!(c instanceof HTMLSelectElement))throw Error('Task Category not found.');c.value='22';if(typeof window.Set_hidCat==='function')window.Set_hidCat();c.dispatchEvent(new Event('change',{bubbles:true}));const h=document.querySelector('#txtHrs');if(!(h instanceof HTMLInputElement))throw Error('Hours field not found.');h.value=String(hours);h.dispatchEvent(new Event('blur',{bubbles:true}));return true};
const taskOpen=()=>{const r=document.querySelector('#select2-ddlTask-container');const t=r?.closest('.select2-selection');if(!(t instanceof HTMLElement))throw Error('Task selector not found.');t.click();return true};
const taskSearch=ticket=>{const e=document.querySelector('.select2-container--open .select2-search__field');if(!(e instanceof HTMLInputElement))throw Error('Task search field not found.');e.focus();e.value=ticket;e.dispatchEvent(new Event('input',{bubbles:true}));e.dispatchEvent(new KeyboardEvent('keyup',{bubbles:true,key:'a'}));return true};
const taskPick=ticket=>{const a=[...document.querySelectorAll('.select2-container--open .select2-results__option')];const o=a.find(x=>x.textContent.includes(ticket));if(!o)throw Error(`Helpdesk task not found: ${ticket}`);o.click();return true};
const save=()=>{const e=document.querySelector('#LnkSave');if(!(e instanceof HTMLElement))throw Error('Save button not found.');e.click();return true};
chrome.tabs.query({active:true,currentWindow:true},([tab])=>{$('date').value=$('date').value||new Date().toISOString().slice(0,10);$('start').addEventListener('click',async()=>{if(!tab?.id)return status('OPM tab not found.');const rows=$('tickets').value.split(/\r?\n/).map(x=>x.trim()).filter(Boolean).map(x=>{const [id,hours]=x.split('|').map(v=>v.trim());return{id,hours}});try{for(let i=0;i<rows.length;i++){const t=rows[i];status(`Ticket ${i+1}/${rows.length}: ${t.id}\nDate`);await run(tab.id,setDate,[$('date').value]);status(`Ticket ${i+1}/${rows.length}: ${t.id}\nProject`);await run(tab.id,changeSelect,['#ddlProj','417','Set_Hid']);await sleep(1500);status(`Ticket ${i+1}/${rows.length}: ${t.id}\nSES`);await run(tab.id,changeSelect,['#ddlTaskType','M','Set_hidType']);await sleep(1500);status(`Ticket ${i+1}/${rows.length}: ${t.id}\nCategory + Hours`);await run(tab.id,categoryHours,[t.hours]);status(`Ticket ${i+1}/${rows.length}: ${t.id}\nOpening Helpdesk task list`);await run(tab.id,taskOpen);await sleep(700);await run(tab.id,taskSearch,[t.id]);await sleep(1500);status(`Ticket ${i+1}/${rows.length}: ${t.id}\nSelecting Helpdesk task`);await run(tab.id,taskPick,[t.id]);await sleep(500);status(`Ticket ${i+1}/${rows.length}: ${t.id}\nSaving`);await run(tab.id,save);await sleep(2000)}status(`Done: ${rows.length} ticket(s) saved.`)}catch(e){status(`Stopped: ${e instanceof Error?e.message:String(e)}`)}})});